name: SSR deploy
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      APP_NAME: aggregator
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm i
      - run: npm test
      - run: npm run ssr:build

      - uses: rlespinasse/github-slug-action@v3.x

      - name: Deploy to stage
        uses: easingthemes/ssh-deploy@v2.1.5
        if: github.event_name == 'push'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSR_STAGE_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSR_STAGE_HOST }}
          REMOTE_USER: ${{ secrets.SSR_STAGE_USER }}
          SOURCE: .
          TARGET: ${{ format('/home/{0}/superhero-ui', secrets.SSR_STAGE_USER) }}
          EXCLUDE: '/.git/, /node_modules/'

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NODE_ENV: production
          TARGET: ${{ format('/home/{0}/superhero-ui', secrets.SSR_STAGE_USER) }}
        with:
          hosts: '${{ secrets.SSR_STAGE_USER }}@${{ secrets.SSR_STAGE_HOST }}'
          privateKey: ${{ secrets.SSR_STAGE_PRIVATE_KEY }}
          debug: true
          command: |
            cd ${{ env.TARGET }}
            npm ci
            killall node
            npm run ssr:start &2> log.log &

      - uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOST: ${{ secrets.SSR_STAGE_HOST }}
        with:
          msg: Deployed to [${{ env.HOST }}](https://${{ env.HOST }}), [bundle report](https://${{ env.HOST }}/report.html)
          check_for_duplicate_msg: true

